// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV2_fpKe0l684-M3U-EjYj-En4Mt0gevU',
    appId: '1:980868120563:web:ef832347db4ea4e92c1c86',
    messagingSenderId: '980868120563',
    projectId: 'careerclaritycompanion-fd4d1',
    authDomain: 'careerclaritycompanion-fd4d1.firebaseapp.com',
    storageBucket: 'careerclaritycompanion-fd4d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrC3GvJ9aColzR0ldkeB2yRYBgD7lbRy0',
    appId: '1:980868120563:android:357000e01d90919f2c1c86',
    messagingSenderId: '980868120563',
    projectId: 'careerclaritycompanion-fd4d1',
    storageBucket: 'careerclaritycompanion-fd4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDywSC0xRRJ-TDuEkG9YnGh1xUyQ250Gkk',
    appId: '1:980868120563:ios:44718919ca97c2312c1c86',
    messagingSenderId: '980868120563',
    projectId: 'careerclaritycompanion-fd4d1',
    storageBucket: 'careerclaritycompanion-fd4d1.firebasestorage.app',
    iosBundleId: 'com.example.careerclaritycompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDywSC0xRRJ-TDuEkG9YnGh1xUyQ250Gkk',
    appId: '1:980868120563:ios:44718919ca97c2312c1c86',
    messagingSenderId: '980868120563',
    projectId: 'careerclaritycompanion-fd4d1',
    storageBucket: 'careerclaritycompanion-fd4d1.firebasestorage.app',
    iosBundleId: 'com.example.careerclaritycompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV2_fpKe0l684-M3U-EjYj-En4Mt0gevU',
    appId: '1:980868120563:web:c2c68af48fb955db2c1c86',
    messagingSenderId: '980868120563',
    projectId: 'careerclaritycompanion-fd4d1',
    authDomain: 'careerclaritycompanion-fd4d1.firebaseapp.com',
    storageBucket: 'careerclaritycompanion-fd4d1.firebasestorage.app',
  );
}
